Add files via upload
one-degree-north/mate-2022-azure pull request #1
Opened 2022-01-20 07:50 UTC by luke780440

2022-01-20 07:52 UTC, luke780440 commented
First iteration

2022-01-20 08:30 UTC, ayambabu23 requested changes
Let me know if you have questions

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +    def __init__(self, port: int, baud_rate: int):
port is not an int, it's a string

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +        self.ser.close()
Good practice, delete once you've seen it

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                if leftJoy_LR < [43,43]:
Questionable line, what are you trying to do?

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                    value = send_value(leftJoy_LR)
self.send_value

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                    value = send_value(leftJoy_LR)
Change for all

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                if rightJoy_LR < [43,43]:
Again, questionable line

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                    packet_rightJoy_stopped = chr(1) + chr(6) + chr((self.value).encode("latin")) + chr(12)
Do chr(0) instead

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                    packet_servoRotate = chr(1) + chr(10) + chr(12)
Do 4 bytes

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +                if servoRotate == True:
Treat servo like you would treat thruster; write code similarly: if the button is held, keep opening. If the button is released, stop opening. If you have questions, come and ask me.

2022-01-20 08:30 UTC, ayambabu23 commented on AzureBot_Test.py
> +    displayGUI = gui.GUI(#add info later)
Comment out this entire line until you've actually done something related to this

2022-01-25 07:23 UTC, luke780440 commented on AzureBot_Test.py
> +            leftJoy_UD = packetControl.packet[1]
I'm a bit confused about what you're trying to say about my code.

2022-01-25 09:34 UTC, luke780440 commented
@ayambabu23 

Please code review

2022-01-26 08:16 UTC, closed without merging